spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/user/**
            - id: vehicle-service
              uri: http://localhost:8085
              predicates:
                - Path=/vehicle/**
  main:
    web-application-type: reactive
